---
version: '2'
run:
  tests: true
linters:
  enable:
    - asasalint
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - ineffassign
    - nilnil
    - nilerr
    - unused
    - wastedassign
  exclusions:
    mispell:
      locale: US
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    gosec:
      severity: low
      confidence: low
      excludes:
        - G115
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
