---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: slurm
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-root
    key: password
    generate: true

  username: slurm
  passwordSecretKeyRef:
    name: mariadb-password
    key: password
    generate: true
  database: slurm_acct_db

  storage:
    size: 1Gi

  replicas: 1

  galera:
    enabled: false

  service:
    type: ClusterIP
  connection:
    secretName: mariadb-conn
    secretTemplate:
      key: dsn
  primaryService:
    type: ClusterIP
  primaryConnection:
    secretName: mariadb-conn-primary
    secretTemplate:
      key: dsn
  secondaryService:
    type: ClusterIP
  secondaryConnection:
    secretName: mariadb-conn-secondary
    secretTemplate:
      key: dsn

  updateStrategy:
    type: ReplicasFirstPrimaryLast

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=4096M
    innodb_lock_wait_timeout=900
    innodb_log_file_size=1024M
    max_allowed_packet=256M

  metrics:
    passwordSecretKeyRef:
      name: mariadb-metrics
      key: password
      generate: true
    enabled: true
